### ISSUE TITLE
Add a schema 

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmnps#10]
* Create schema for returning parameters [here](https://github.com/sdss/lvmnps/blob/746394ba7f55a7c770bae25e21fb03df9e18f171/python/lvmnps/actor/actor.py#L39) as temporary non self, [eg](https://github.com/sdss/lvmtan/blob/54d57ba01bdf7b9b65cd5346f8473ca0786aeb3a/python/lvmtan/BasdaCluPythonServiceWorker.py#L48):

       schema = {
           "type": "object",
           "properties": {
               "State": {"type": "string"},
               "Units": {"type": "string"},
         },
        "additionalProperties": False
       }

* Add extra parameters maybe as an extra static member [here](https://github.com/sdss/lvmnps/blob/746394ba7f55a7c770bae25e21fb03df9e18f171/python/lvmnps/switch/outlet.py#L49)
* Load schema into the actor, [see here](https://github.com/sdss/lvmtan/blob/54d57ba01bdf7b9b65cd5346f8473ca0786aeb3a/python/lvmtan/BasdaCluPythonServiceWorker.py#L89)

**Comment by mmingyeong** [comment]
update done

**Comment by wasndas** [comment]
https://clu.readthedocs.io/en/latest/keyword-model.html

**Comment by mmingyeong** [comment]
Sorry I misunderstood. I added only json configuration file and not schema. I will add it.

**Comment by wasndas** [comment]
I whould add the schema directly into the code passing it to the actor directly. Have to ask Jose if this the way to go, at least I have done it that way for lvmtan.

**Comment by wasndas** [comment]
Also dont know if the return parameters should be CAPITAL, CamelCase or lowercase, currently they are CAPITAL in lvmnps.

**Comment by wasndas** [comment]
... here is a patch for adding a json schema inside the code.

```
diff --git a/python/lvmnps/actor/actor.py b/python/lvmnps/actor/actor.py
index b3a36d1..da0fd47 100644
--- a/python/lvmnps/actor/actor.py
+++ b/python/lvmnps/actor/actor.py
@@ -31,6 +31,19 @@ class lvmnps(AMQPActor):
 
     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
+        self.schema = {
+                    "type": "object",
+                    "properties": {},
+                    "patternProperties": {
+                     "^[A-Za-z0-9_.]+$": {
+                           "STATE": {"type": "string"},
+                           "DESCR": {"type": "string"},
+                           "SWITCH": {"type": "string"},
+                           "PORT": {"type": "number"},
+                    },
+                    "additionalProperties": False,
+                }
+        }
 
     async def start(self):
         await super().start()
@@ -47,7 +60,10 @@ class lvmnps(AMQPActor):
             except Exception as ex:
                 self.log.error(f"Unexpected exception {type(ex)}: {ex}")
 
+        self.load_schema(self.schema, is_file=False)
+
         self.log.debug("Start done")
+        self.log.debug(str(self.schema))
 
     async def stop(self):
         with suppress(asyncio.CancelledError):

```
