### ISSUE TITLE
The python print funcion is evil

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmnps#21]
Please dont use print, instead use the sdss logger.

**Comment by mmingyeong** [comment]
Yes. I used print for debugging but I agree that I should use the sdss logger. I will update that. Thank you for the comment

**Comment by wasndas** [comment]
... and close the tickets when they are done ,-)

**Comment by mmingyeong** [comment]
I deleted print and modified lvmpower.py which used SDSS logger.
