### ISSUE TITLE
Remove multiple key "num" from config files.

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmnps#23]
https://github.com/sdss/lvmnps/blob/master/python/lvmnps/etc/lvmnps_dli.yml#L13
... in line 13, 17, 21, 24, 27, ...

Maybe I should have named the key _num_ with something more describing: _number_of_ports_,
this key defines the number of ports the powerswitch hardware supports.

The key is used only here:
 https://github.com/sdss/lvmnps/blob/master/python/lvmnps/switch/powerswitchbase.py#L26

**Comment by changgonKim** [comment]
Thanks! I will change that
