### ISSUE TITLE
Handling of port description config vs hardware

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmnps#7]
Currently the description of a port is done by the config file, maybe a simple script or an option while startup to upload the port description from the config to the dli hardware might be good to have.

**Comment by mmingyeong** [comment]
I updated the configuration file(yml) containing the description of a port. You can confirm 'lvmnps_dli.yml' Thank you for comment!

**Comment by wasndas** [comment]
Maybe I havent found the code for this functionality or the description was misleading. The ideas was to upload the description from the config file directly to the hardware with an option or an extra utility program, eg if the powerswitch is exchanged, so that it has the same description in the hardware web interface as in the config file.

**Comment by mmingyeong** [comment]
I misunderstood your comment. Now I see. You mean that the hardware web interface will be updated automatically, if we changes the configuration file, or vice versa? I've kept updating the configuration file directly by hand, but I agree that we need that functionality. I will try to add script for this.

**Comment by wasndas** [comment]
Yes that was the idea, I whould update the hardware web interface from the config file. Actually I had a problem with another projects pdu, when a port was broken and I had to change the port and didnt have something like this feature ,-)
