### ISSUE TITLE
Add an actor command interface for powercycle

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmnps#8]
Some hardware pieces do not like fast off/on power cycles, so a powercycle actor command should be added, similar to the [Dli Powercycle](https://github.com/sdss/lvmnps/blob/15e7a9c2abb53801a778431d19c27686bf12a2d6/python/lvmnps/switch/dli/dlipower.py#L494), OFF -> WAIT -> ON

**Comment by mmingyeong** [comment]
I added 'cycle' command. But, I keep testing this one  (containing on,off, and cycle) Thank you for comment
